[project]
name = 'examples'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.vulnbank]
path = 'contracts/vulnbank.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
